import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { supabase } from '../lib/supabase'
import { useAuth } from '../context/AuthContext'
import logoImage from '../CoachRICE_White.png'

const agreements = [
  {
    id: "data-privacy",
    title: "Data Use & Privacy",
    icon: "🔒",
    summary: "How we collect, store, and use your app activity.",
    full: `By using the CoachRICE Toolkit, you agree that the Doerr Institute for New Leaders collects and stores your activity within the app, including practice exam responses, AI coaching session transcripts, AI-generated feedback, and progress history. This data is stored indefinitely unless you submit a deletion request to Doerr Institute staff.

Your data may be accessed by Doerr Institute staff for individual progress review and aggregate program analysis. It may also be used to improve program design and tool performance, including understanding cohort-level growth areas and refining AI feedback systems. The CoachRICE Toolkit uses the Anthropic API; your data is not used by Anthropic to train its models.`,
  },
  {
    id: "client-confidentiality",
    title: "Confidentiality of Client Data",
    icon: "🤝",
    summary: "Your responsibility when uploading coaching materials.",
    full: `You are solely responsible for ensuring that any coaching session transcripts or materials you upload have been de-identified and contain no personally identifiable information (PII) belonging to your clients or any third party. You affirm that you have obtained any necessary consent before uploading materials involving other individuals. The Doerr Institute is not liable for any breach of client confidentiality resulting from your uploads.

Please note: uploaded transcripts are not stored by the CoachRICE Toolkit. Only the AI-generated feedback produced from your transcript is retained in your account history.`,
  },
  {
    id: "acceptable-use",
    title: "Acceptable Use",
    icon: "✅",
    summary: "Appropriate use of the toolkit and your account.",
    full: `You agree to use the CoachRICE Toolkit solely for coaching education and professional development purposes. You will not share your login credentials or allow others to access your account. Misuse of any AI-powered features for purposes outside of coaching education is prohibited.`,
  },
  {
    id: "program-access",
    title: "Program Access & Account Terms",
    icon: "📅",
    summary: "Free access during enrollment; deactivation after one year.",
    full: `Access to the CoachRICE Toolkit is provided free of charge during your active enrollment period, defined as one year from your program orientation date. At the end of your enrollment period, your account will be deactivated. To request access to or deletion of your data after deactivation, contact the Doerr Institute directly.`,
  },
  {
    id: "ai-disclaimer",
    title: "AI-Generated Content Disclaimer",
    icon: "🤖",
    summary: "AI feedback is developmental only — not an official ICF evaluation.",
    full: `Feedback generated by the CoachRICE Toolkit — including transcript analysis and coaching session feedback — is produced by artificial intelligence and is intended for developmental purposes only. It does not constitute an official ICF evaluation, formal coaching assessment, or substitute for feedback from a qualified human mentor coach.`,
  },
  {
    id: "beta-resource",
    title: "Beta Resource Acknowledgment",
    icon: "⚠️",
    summary: "This tool is in development. Use discernment.",
    full: `The CoachRICE Toolkit is a bonus resource currently in development. As such, it may experience outages, disruptions, or produce inaccurate results. It is imperative that you use discernment when interpreting any feedback or results generated by this tool. The Doerr Institute does not guarantee uninterrupted access or the accuracy of AI-generated content at any time.

Please report any app difficulties, errors, or unexpected behavior to coachrice@rice.edu.`,
  },
];

export default function Agreements() {
  const navigate = useNavigate()
  const { user, profile, loading } = useAuth()
  const [error, setError] = useState(null)
  const [submitting, setSubmitting] = useState(false)
  const [checked, setChecked] = useState({})
  const [expanded, setExpanded] = useState(null)

  // Debug logging
  if (!loading) {
    console.log('Agreements page state:', { user: user?.id, profile, loading })
  }

  // If not logged in, redirect to login
  if (!loading && !user) {
    console.log('No user, redirecting to login')
    navigate('/login', { replace: true })
    return
  }

  // If already accepted, redirect to dashboard
  if (!loading && user && profile && profile.agreements_accepted) {
    console.log('Agreements already accepted, redirecting to dashboard')
    navigate('/dashboard', { replace: true })
    return
  }

  const allChecked = agreements.every((a) => checked[a.id]);

  const toggle = (id) => {
    setChecked((prev) => ({ ...prev, [id]: !prev[id] }));
  };

  const toggleExpand = (id) => {
    setExpanded((prev) => (prev === id ? null : id));
  };

  const handleComplete = async () => {
    console.log('handleComplete called, user:', user?.id)

    if (!user || !user.id) {
      console.error('User or user.id missing:', user)
      setError('Auth session missing. Please log in again.')
      return
    }

    setSubmitting(true)
    setError(null)

    try {
      // First check if user profile exists
      if (!profile) {
        console.log('No profile found, this might be a new user')
        // User might not have a profile row yet, try to create one
        const { error: insertError } = await supabase
          .from('users')
          .insert([{ id: user.id, email: user.email, agreements_accepted: true, agreements_accepted_at: new Date().toISOString() }])
          .select()

        if (insertError && !insertError.message.includes('duplicate')) {
          console.error('Insert error:', insertError)
          throw insertError
        }
      } else {
        // Profile exists, just update it
        const { error: updateError } = await supabase
          .from('users')
          .update({ agreements_accepted: true, agreements_accepted_at: new Date().toISOString() })
          .eq('id', user.id)

        if (updateError) {
          console.error('Update error:', updateError)
          throw updateError
        }
      }

      console.log('Successfully saved agreements')
      navigate('/dashboard', { replace: true })
    } catch (err) {
      console.error('Error accepting agreements:', err)
      setError(`Failed to save your acceptance: ${err.message || 'Unknown error'}. Please try again.`)
      setSubmitting(false)
    }
  }

  if (loading || !user) {
    return (
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', minHeight: '100vh', fontFamily: "'Montserrat', sans-serif" }}>
        <div style={{ textAlign: 'center' }}>
          <div style={{ fontSize: '18px', fontWeight: '600', color: '#00205B', marginBottom: '8px' }}>Loading…</div>
          <div style={{ fontSize: '13px', color: '#6b7a99' }}>Verifying your session</div>
        </div>
      </div>
    )
  }

  return (
    <div style={s.container}>
      <div style={s.brandPanel}>
        <div style={s.brandBlobTop} />
        <div style={s.brandBlobBottom} />
        <div style={s.brandLogo}>
          <img src={logoImage} alt="CoachRICE" style={{ height: '44px', maxWidth: '160px', objectFit: 'contain' }} />
        </div>
        <div style={s.brandBody}>
          <div style={s.brandEyebrow}>Terms & Conditions</div>
          <div style={s.brandTitle}>Before You Begin</div>
          <div style={s.brandSub}>Please review and acknowledge each agreement to access the CoachRICE Toolkit.</div>
        </div>
        <div style={s.brandHelp}>
          <div style={s.brandHelpTitle}>Questions?</div>
          <div style={s.brandHelpBody}>Contact <a href="mailto:coachrice@rice.edu" style={{ color: '#69cce6', textDecoration: 'none' }}>coachrice@rice.edu</a></div>
        </div>
      </div>

      <div style={s.formPanel}>
        <div style={s.formInner}>
          <div style={s.progressRow}>
            <span style={s.progressLabel}>
              {Object.values(checked).filter(Boolean).length} of {agreements.length} acknowledged
            </span>
            <div style={s.progressBar}>
              <div
                style={{
                  ...s.progressFill,
                  width: `${(Object.values(checked).filter(Boolean).length / agreements.length) * 100}%`,
                }}
              />
            </div>
          </div>

          <div style={s.list}>
            {agreements.map((a, i) => {
              const isOpen = expanded === a.id;
              const isChecked = !!checked[a.id];
              return (
                <div
                  key={a.id}
                  style={{
                    ...s.card,
                    borderColor: isChecked ? "#69cce6" : "#e2e8f0",
                    background: isChecked ? "#f0fbfe" : "#ffffff",
                  }}
                >
                  <div style={s.cardTop}>
                    <div style={s.cardLeft}>
                      <span style={s.icon}>{a.icon}</span>
                      <div>
                        <div style={s.cardTitle}>
                          <span style={s.cardNumber}>{String(i + 1).padStart(2, "0")}</span>
                          {a.title}
                        </div>
                        <div style={s.cardSummary}>{a.summary}</div>
                      </div>
                    </div>
                    <div style={s.cardRight}>
                      <button
                        onClick={() => toggleExpand(a.id)}
                        style={s.readBtn}
                      >
                        {isOpen ? "Close ▲" : "Read ▼"}
                      </button>
                    </div>
                  </div>

                  {isOpen && (
                    <div style={s.fullText}>
                      {a.full.split("\n\n").map((para, idx) => (
                        <p key={idx} style={s.para}>
                          {para.includes("coachrice@rice.edu") ? (
                            <>
                              {para.split("coachrice@rice.edu")[0]}
                              <a href="mailto:coachrice@rice.edu" style={s.link}>
                                coachrice@rice.edu
                              </a>
                              {para.split("coachrice@rice.edu")[1]}
                            </>
                          ) : (
                            para
                          )}
                        </p>
                      ))}
                    </div>
                  )}

                  <label style={s.checkRow}>
                    <input
                      type="checkbox"
                      checked={isChecked}
                      onChange={() => toggle(a.id)}
                      style={s.checkbox}
                    />
                    <span style={{ ...s.checkLabel, color: isChecked ? "#00205B" : "#7C7E7F" }}>
                      {isChecked ? "✓ Acknowledged" : "I have read and acknowledge this agreement"}
                    </span>
                  </label>
                </div>
              );
            })}
          </div>

          {error && <p style={s.errorMsg}>{error}</p>}

          <button
            onClick={handleComplete}
            disabled={!allChecked || submitting}
            style={{
              ...s.btnSignin,
              background: (allChecked && !submitting) ? "#00205B" : "#c9d4e3",
              cursor: (allChecked && !submitting) ? "pointer" : "not-allowed",
            }}
          >
            {submitting ? 'Saving…' : 'Enter CoachRICE Toolkit →'}
          </button>
        </div>
      </div>
    </div>
  )
}

const s = {
  container: {
    display: 'flex',
    minHeight: '100vh',
    fontFamily: "'Montserrat', sans-serif",
  },
  brandPanel: {
    flex: '1',
    background: 'linear-gradient(135deg, #00205B 0%, #002a7a 100%)',
    color: '#fff',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    padding: '60px 48px',
    position: 'relative',
    overflow: 'hidden',
  },
  brandBlobTop: {
    position: 'absolute',
    top: '-80px',
    right: '-80px',
    width: '160px',
    height: '160px',
    borderRadius: '50%',
    background: 'rgba(105,204,230,0.07)',
  },
  brandBlobBottom: {
    position: 'absolute',
    bottom: '40px',
    left: '-40px',
    width: '160px',
    height: '160px',
    borderRadius: '50%',
    background: 'rgba(255,130,0,0.07)',
  },
  brandLogo: {
    position: 'relative',
    zIndex: 1,
    marginBottom: '60px',
  },
  brandBody: {
    flex: '1',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    position: 'relative',
    zIndex: 1,
  },
  brandTitle: {
    fontSize: '26px',
    fontWeight: '800',
    color: '#fff',
    lineHeight: '1.2',
    marginBottom: '16px',
    letterSpacing: '-0.5px',
  },
  brandSub: {
    fontSize: '12px',
    color: 'rgba(255,255,255,0.55)',
    lineHeight: '1.7',
  },
  brandEyebrow: {
    fontSize: '10px',
    fontWeight: '700',
    letterSpacing: '1.6px',
    textTransform: 'uppercase',
    color: '#69cce6',
    marginBottom: '14px',
  },
  brandHelp: {
    background: 'rgba(255,255,255,0.06)',
    borderRadius: '10px',
    padding: '14px 18px',
    marginTop: '24px',
    position: 'relative',
    zIndex: 1,
  },
  brandHelpTitle: {
    fontSize: '10px',
    fontWeight: '700',
    color: '#69cce6',
    marginBottom: '4px',
  },
  brandHelpBody: {
    fontSize: '10px',
    color: 'rgba(255,255,255,0.55)',
    lineHeight: '1.6',
  },
  formPanel: {
    flex: '1',
    background: '#fff',
    display: 'flex',
    flexDirection: 'column',
    padding: '40px 32px',
    overflow: 'auto',
  },
  formInner: {
    width: '100%',
    maxWidth: '520px',
  },
  progressRow: {
    marginBottom: '28px',
  },
  progressLabel: {
    fontSize: '12px',
    fontWeight: '600',
    color: '#00205B',
    letterSpacing: '0.05em',
    display: 'block',
    marginBottom: '8px',
  },
  progressBar: {
    height: '4px',
    background: '#e2e8f0',
    borderRadius: '99px',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    background: '#00205B',
    borderRadius: '99px',
    transition: 'width 0.4s ease',
  },
  list: {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
    marginBottom: '24px',
  },
  card: {
    borderRadius: '10px',
    border: '1.5px solid',
    padding: '16px 18px',
    transition: 'all 0.2s ease',
  },
  cardTop: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: '12px',
  },
  cardLeft: {
    display: 'flex',
    gap: '12px',
    alignItems: 'flex-start',
    flex: 1,
  },
  icon: {
    fontSize: '18px',
    lineHeight: 1,
    marginTop: '1px',
    flexShrink: 0,
  },
  cardTitle: {
    fontSize: '13px',
    fontWeight: '700',
    color: '#00205B',
    marginBottom: '2px',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  cardNumber: {
    fontSize: '10px',
    fontWeight: '700',
    color: '#78b3e0',
    letterSpacing: '0.08em',
  },
  cardSummary: {
    fontSize: '12px',
    color: '#6b7a99',
    fontWeight: '400',
    lineHeight: '1.4',
  },
  cardRight: {
    flexShrink: 0,
  },
  readBtn: {
    background: 'none',
    border: '1px solid #78b3e0',
    color: '#00205B',
    borderRadius: '5px',
    padding: '4px 10px',
    fontSize: '10px',
    fontWeight: '600',
    cursor: 'pointer',
    fontFamily: "'Montserrat', sans-serif",
    letterSpacing: '0.05em',
    whiteSpace: 'nowrap',
  },
  fullText: {
    marginTop: '12px',
    paddingTop: '12px',
    borderTop: '1px solid #e2e8f0',
  },
  para: {
    fontSize: '12px',
    lineHeight: '1.6',
    color: '#374151',
    margin: '0 0 10px',
  },
  link: {
    color: '#00205B',
    fontWeight: '600',
    textDecoration: 'underline',
  },
  checkRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    marginTop: '12px',
    cursor: 'pointer',
    paddingTop: '12px',
    borderTop: '1px dashed #e2e8f0',
  },
  checkbox: {
    width: '16px',
    height: '16px',
    accentColor: '#00205B',
    cursor: 'pointer',
    flexShrink: 0,
  },
  checkLabel: {
    fontSize: '12px',
    fontWeight: '600',
    userSelect: 'none',
  },
  btnSignin: {
    width: '100%',
    height: '44px',
    borderRadius: '7px',
    color: '#fff',
    border: 'none',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: '700',
    fontFamily: "'Montserrat', sans-serif",
    letterSpacing: '0.3px',
    transition: 'background 0.15s',
  },
  errorMsg: {
    color: '#00205B',
    fontSize: '10px',
    background: '#fff3e6',
    border: '1px solid #ffe0b2',
    borderRadius: '6px',
    padding: '10px 12px',
    marginBottom: '12px',
  },
}
