import { useState } from "react";

const agreements = [
  {
    id: "data-privacy",
    title: "Data Use & Privacy",
    icon: "🔒",
    summary: "How we collect, store, and use your app activity.",
    full: `By using the CoachRICE Toolkit, you agree that the Doerr Institute for New Leaders collects and stores your activity within the app, including practice exam responses, AI coaching session transcripts, AI-generated feedback, and progress history. This data is stored indefinitely unless you submit a deletion request to Doerr Institute staff.

Your data may be accessed by Doerr Institute staff for individual progress review and aggregate program analysis. It may also be used to improve program design and tool performance, including understanding cohort-level growth areas and refining AI feedback systems. The CoachRICE Toolkit uses the Anthropic API; your data is not used by Anthropic to train its models.`,
  },
  {
    id: "client-confidentiality",
    title: "Confidentiality of Client Data",
    icon: "🤝",
    summary: "Your responsibility when uploading coaching materials.",
    full: `You are solely responsible for ensuring that any coaching session transcripts or materials you upload have been de-identified and contain no personally identifiable information (PII) belonging to your clients or any third party. You affirm that you have obtained any necessary consent before uploading materials involving other individuals. The Doerr Institute is not liable for any breach of client confidentiality resulting from your uploads.

Please note: uploaded transcripts are not stored by the CoachRICE Toolkit. Only the AI-generated feedback produced from your transcript is retained in your account history.`,
  },
  {
    id: "acceptable-use",
    title: "Acceptable Use",
    icon: "✅",
    summary: "Appropriate use of the toolkit and your account.",
    full: `You agree to use the CoachRICE Toolkit solely for coaching education and professional development purposes. You will not share your login credentials or allow others to access your account. Misuse of any AI-powered features for purposes outside of coaching education is prohibited.`,
  },
  {
    id: "program-access",
    title: "Program Access & Account Terms",
    icon: "📅",
    summary: "Free access during enrollment; deactivation after one year.",
    full: `Access to the CoachRICE Toolkit is provided free of charge during your active enrollment period, defined as one year from your program orientation date. At the end of your enrollment period, your account will be deactivated. To request access to or deletion of your data after deactivation, contact the Doerr Institute directly.`,
  },
  {
    id: "ai-disclaimer",
    title: "AI-Generated Content Disclaimer",
    icon: "🤖",
    summary: "AI feedback is developmental only — not an official ICF evaluation.",
    full: `Feedback generated by the CoachRICE Toolkit — including transcript analysis and coaching session feedback — is produced by artificial intelligence and is intended for developmental purposes only. It does not constitute an official ICF evaluation, formal coaching assessment, or substitute for feedback from a qualified human mentor coach.`,
  },
  {
    id: "beta-resource",
    title: "Beta Resource Acknowledgment",
    icon: "⚠️",
    summary: "This tool is in development. Use discernment.",
    full: `The CoachRICE Toolkit is a bonus resource currently in development. As such, it may experience outages, disruptions, or produce inaccurate results. It is imperative that you use discernment when interpreting any feedback or results generated by this tool. The Doerr Institute does not guarantee uninterrupted access or the accuracy of AI-generated content at any time.

Please report any app difficulties, errors, or unexpected behavior to coachrice@rice.edu.`,
  },
];

export default function CoachRICEAgreements({ onComplete }) {
  const [checked, setChecked] = useState({});
  const [expanded, setExpanded] = useState(null);

  const allChecked = agreements.every((a) => checked[a.id]);

  const toggle = (id) => {
    setChecked((prev) => ({ ...prev, [id]: !prev[id] }));
  };

  const toggleExpand = (id) => {
    setExpanded((prev) => (prev === id ? null : id));
  };

  const handleSubmit = () => {
    if (allChecked && onComplete) onComplete();
  };

  return (
    <div style={styles.wrapper}>
      <link
        href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700;800&display=swap"
        rel="stylesheet"
      />

      {/* Header */}
      <div style={styles.header}>
        <div style={styles.logoRow}>
          <div style={styles.logoMark} />
          <span style={styles.logoText}>CoachRICE Toolkit</span>
        </div>
        <h1 style={styles.headline}>Before You Begin</h1>
        <p style={styles.subheadline}>
          Please review and acknowledge each agreement to access the toolkit.
        </p>
        <div style={styles.progressRow}>
          <span style={styles.progressLabel}>
            {Object.values(checked).filter(Boolean).length} of {agreements.length} acknowledged
          </span>
          <div style={styles.progressBar}>
            <div
              style={{
                ...styles.progressFill,
                width: `${(Object.values(checked).filter(Boolean).length / agreements.length) * 100}%`,
              }}
            />
          </div>
        </div>
      </div>

      {/* Agreements */}
      <div style={styles.list}>
        {agreements.map((a, i) => {
          const isOpen = expanded === a.id;
          const isChecked = !!checked[a.id];
          return (
            <div
              key={a.id}
              style={{
                ...styles.card,
                borderColor: isChecked ? "#69cce6" : "#e2e8f0",
                background: isChecked ? "#f0fbfe" : "#ffffff",
              }}
            >
              <div style={styles.cardTop}>
                <div style={styles.cardLeft}>
                  <span style={styles.icon}>{a.icon}</span>
                  <div>
                    <div style={styles.cardTitle}>
                      <span style={styles.cardNumber}>{String(i + 1).padStart(2, "0")}</span>
                      {a.title}
                    </div>
                    <div style={styles.cardSummary}>{a.summary}</div>
                  </div>
                </div>
                <div style={styles.cardRight}>
                  <button
                    onClick={() => toggleExpand(a.id)}
                    style={styles.readBtn}
                  >
                    {isOpen ? "Close ▲" : "Read ▼"}
                  </button>
                </div>
              </div>

              {isOpen && (
                <div style={styles.fullText}>
                  {a.full.split("\n\n").map((para, idx) => (
                    <p key={idx} style={styles.para}>
                      {para.includes("coachrice@rice.edu") ? (
                        <>
                          {para.split("coachrice@rice.edu")[0]}
                          <a href="mailto:coachrice@rice.edu" style={styles.link}>
                            coachrice@rice.edu
                          </a>
                          {para.split("coachrice@rice.edu")[1]}
                        </>
                      ) : (
                        para
                      )}
                    </p>
                  ))}
                </div>
              )}

              <label style={styles.checkRow}>
                <input
                  type="checkbox"
                  checked={isChecked}
                  onChange={() => toggle(a.id)}
                  style={styles.checkbox}
                />
                <span style={{ ...styles.checkLabel, color: isChecked ? "#00205B" : "#7C7E7F" }}>
                  {isChecked ? "✓ Acknowledged" : "I have read and acknowledge this agreement"}
                </span>
              </label>
            </div>
          );
        })}
      </div>

      {/* Footer CTA */}
      <div style={styles.footer}>
        {!allChecked && (
          <p style={styles.footerHint}>
            Please acknowledge all {agreements.length} agreements to continue.
          </p>
        )}
        <button
          onClick={handleSubmit}
          disabled={!allChecked}
          style={{
            ...styles.ctaBtn,
            background: allChecked ? "#00205B" : "#c9d4e3",
            cursor: allChecked ? "pointer" : "not-allowed",
            transform: allChecked ? "none" : "none",
          }}
        >
          {allChecked ? "Enter CoachRICE Toolkit →" : "Acknowledge All Agreements to Continue"}
        </button>
        <p style={styles.footerNote}>
          Questions? Contact{" "}
          <a href="mailto:coachrice@rice.edu" style={styles.link}>
            coachrice@rice.edu
          </a>
        </p>
      </div>
    </div>
  );
}

const styles = {
  wrapper: {
    fontFamily: "'Montserrat', sans-serif",
    minHeight: "100vh",
    background: "linear-gradient(160deg, #f8fafc 0%, #eef4fb 100%)",
    padding: "0 0 60px 0",
  },
  header: {
    background: "#00205B",
    color: "#fff",
    padding: "48px 32px 40px",
    textAlign: "center",
  },
  logoRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
    marginBottom: "24px",
  },
  logoMark: {
    width: "10px",
    height: "32px",
    background: "#69cce6",
    borderRadius: "2px",
  },
  logoText: {
    fontSize: "13px",
    fontWeight: "700",
    letterSpacing: "0.15em",
    textTransform: "uppercase",
    color: "#78b3e0",
  },
  headline: {
    fontSize: "32px",
    fontWeight: "800",
    margin: "0 0 10px",
    letterSpacing: "-0.5px",
  },
  subheadline: {
    fontSize: "15px",
    fontWeight: "400",
    color: "#b8d0ee",
    margin: "0 0 28px",
  },
  progressRow: {
    maxWidth: "400px",
    margin: "0 auto",
  },
  progressLabel: {
    fontSize: "12px",
    fontWeight: "600",
    color: "#69cce6",
    letterSpacing: "0.05em",
    display: "block",
    marginBottom: "8px",
  },
  progressBar: {
    height: "4px",
    background: "rgba(255,255,255,0.15)",
    borderRadius: "99px",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    background: "#69cce6",
    borderRadius: "99px",
    transition: "width 0.4s ease",
  },
  list: {
    maxWidth: "720px",
    margin: "40px auto 0",
    padding: "0 20px",
    display: "flex",
    flexDirection: "column",
    gap: "14px",
  },
  card: {
    borderRadius: "12px",
    border: "1.5px solid",
    padding: "20px 24px",
    transition: "all 0.2s ease",
    boxShadow: "0 1px 4px rgba(0,0,0,0.05)",
  },
  cardTop: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: "12px",
  },
  cardLeft: {
    display: "flex",
    gap: "14px",
    alignItems: "flex-start",
    flex: 1,
  },
  icon: {
    fontSize: "22px",
    lineHeight: 1,
    marginTop: "2px",
    flexShrink: 0,
  },
  cardTitle: {
    fontSize: "15px",
    fontWeight: "700",
    color: "#00205B",
    marginBottom: "4px",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  cardNumber: {
    fontSize: "11px",
    fontWeight: "700",
    color: "#78b3e0",
    letterSpacing: "0.08em",
  },
  cardSummary: {
    fontSize: "13px",
    color: "#7C7E7F",
    fontWeight: "400",
    lineHeight: "1.5",
  },
  cardRight: {
    flexShrink: 0,
  },
  readBtn: {
    background: "none",
    border: "1px solid #78b3e0",
    color: "#00205B",
    borderRadius: "6px",
    padding: "5px 12px",
    fontSize: "11px",
    fontWeight: "600",
    cursor: "pointer",
    fontFamily: "'Montserrat', sans-serif",
    letterSpacing: "0.05em",
    whiteSpace: "nowrap",
  },
  fullText: {
    marginTop: "16px",
    paddingTop: "16px",
    borderTop: "1px solid #e2e8f0",
  },
  para: {
    fontSize: "13px",
    lineHeight: "1.75",
    color: "#374151",
    margin: "0 0 12px",
  },
  link: {
    color: "#00205B",
    fontWeight: "600",
    textDecoration: "underline",
  },
  checkRow: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    marginTop: "16px",
    cursor: "pointer",
    paddingTop: "14px",
    borderTop: "1px dashed #e2e8f0",
  },
  checkbox: {
    width: "18px",
    height: "18px",
    accentColor: "#00205B",
    cursor: "pointer",
    flexShrink: 0,
  },
  checkLabel: {
    fontSize: "13px",
    fontWeight: "600",
    userSelect: "none",
  },
  footer: {
    maxWidth: "720px",
    margin: "32px auto 0",
    padding: "0 20px",
    textAlign: "center",
  },
  footerHint: {
    fontSize: "13px",
    color: "#7C7E7F",
    marginBottom: "14px",
  },
  ctaBtn: {
    color: "#fff",
    border: "none",
    borderRadius: "10px",
    padding: "16px 36px",
    fontSize: "15px",
    fontWeight: "700",
    fontFamily: "'Montserrat', sans-serif",
    letterSpacing: "0.03em",
    transition: "background 0.2s ease",
    width: "100%",
    maxWidth: "480px",
  },
  footerNote: {
    marginTop: "16px",
    fontSize: "12px",
    color: "#7C7E7F",
  },
};
